/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiRecoveryRouteImport } from './routes/api.recovery'
import { Route as ApiRegistrationsRouteImport } from './routes/api.registrations'
import { Route as ApiTournamentsRouteImport } from './routes/api.tournaments'
import { Route as HealthDatabaseRouteImport } from './routes/health.database'
import { Route as ResultsCodeRouteImport } from './routes/results.$code'
import { Route as WatchCodeRouteImport } from './routes/watch.$code'
import { Route as ApiAdminActionRouteImport } from './routes/api.admin.$action'
import { Route as ApiAdminLogoRouteImport } from './routes/api.admin.logo'
import { Route as ApiAssetsIdRouteImport } from './routes/api.assets.$id'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthPasswordRouteImport } from './routes/api.auth.password'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api.auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecoveryRoute = ApiRecoveryRouteImport.update({
  id: '/api/recovery',
  path: '/api/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsRoute = ApiRegistrationsRouteImport.update({
  id: '/api/registrations',
  path: '/api/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentsRoute = ApiTournamentsRouteImport.update({
  id: '/api/tournaments',
  path: '/api/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthDatabaseRoute = HealthDatabaseRouteImport.update({
  id: '/health/database',
  path: '/health/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsCodeRoute = ResultsCodeRouteImport.update({
  id: '/results/$code',
  path: '/results/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchCodeRoute = WatchCodeRouteImport.update({
  id: '/watch/$code',
  path: '/watch/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActionRoute = ApiAdminActionRouteImport.update({
  id: '/api/admin/$action',
  path: '/api/admin/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoRoute = ApiAdminLogoRouteImport.update({
  id: '/api/admin/logo',
  path: '/api/admin/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsIdRoute = ApiAssetsIdRouteImport.update({
  id: '/api/assets/$id',
  path: '/api/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/health/database': typeof HealthDatabaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/watch/$code': typeof WatchCodeRoute
  '/api/admin/$action': typeof ApiAdminActionRoute
  '/api/admin/logo': typeof ApiAdminLogoRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/health/database': typeof HealthDatabaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/watch/$code': typeof WatchCodeRoute
  '/api/admin/$action': typeof ApiAdminActionRoute
  '/api/admin/logo': typeof ApiAdminLogoRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/developer': typeof DeveloperRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/health/database': typeof HealthDatabaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/watch/$code': typeof WatchCodeRoute
  '/api/admin/$action': typeof ApiAdminActionRoute
  '/api/admin/logo': typeof ApiAdminLogoRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/developer'
    | '/register'
    | '/sitemap.xml'
    | '/api/recovery'
    | '/api/registrations'
    | '/api/tournaments'
    | '/health/database'
    | '/results/$code'
    | '/watch/$code'
    | '/api/admin/$action'
    | '/api/admin/logo'
    | '/api/assets/$id'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/developer'
    | '/register'
    | '/sitemap.xml'
    | '/api/recovery'
    | '/api/registrations'
    | '/api/tournaments'
    | '/health/database'
    | '/results/$code'
    | '/watch/$code'
    | '/api/admin/$action'
    | '/api/admin/logo'
    | '/api/assets/$id'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/developer'
    | '/register'
    | '/sitemap.xml'
    | '/api/recovery'
    | '/api/registrations'
    | '/api/tournaments'
    | '/health/database'
    | '/results/$code'
    | '/watch/$code'
    | '/api/admin/$action'
    | '/api/admin/logo'
    | '/api/assets/$id'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DeveloperRoute: typeof DeveloperRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiRecoveryRoute: typeof ApiRecoveryRoute
  ApiRegistrationsRoute: typeof ApiRegistrationsRoute
  ApiTournamentsRoute: typeof ApiTournamentsRoute
  HealthDatabaseRoute: typeof HealthDatabaseRoute
  ResultsCodeRoute: typeof ResultsCodeRoute
  WatchCodeRoute: typeof WatchCodeRoute
  ApiAdminActionRoute: typeof ApiAdminActionRoute
  ApiAdminLogoRoute: typeof ApiAdminLogoRoute
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recovery': {
      id: '/api/recovery'
      path: '/api/recovery'
      fullPath: '/api/recovery'
      preLoaderRoute: typeof ApiRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations': {
      id: '/api/registrations'
      path: '/api/registrations'
      fullPath: '/api/registrations'
      preLoaderRoute: typeof ApiRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournaments': {
      id: '/api/tournaments'
      path: '/api/tournaments'
      fullPath: '/api/tournaments'
      preLoaderRoute: typeof ApiTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/database': {
      id: '/health/database'
      path: '/health/database'
      fullPath: '/health/database'
      preLoaderRoute: typeof HealthDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$code': {
      id: '/results/$code'
      path: '/results/$code'
      fullPath: '/results/$code'
      preLoaderRoute: typeof ResultsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$code': {
      id: '/watch/$code'
      path: '/watch/$code'
      fullPath: '/watch/$code'
      preLoaderRoute: typeof WatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$action': {
      id: '/api/admin/$action'
      path: '/api/admin/$action'
      fullPath: '/api/admin/$action'
      preLoaderRoute: typeof ApiAdminActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logo': {
      id: '/api/admin/logo'
      path: '/api/admin/logo'
      fullPath: '/api/admin/logo'
      preLoaderRoute: typeof ApiAdminLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/api/assets/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DeveloperRoute: DeveloperRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiRecoveryRoute: ApiRecoveryRoute,
  ApiRegistrationsRoute: ApiRegistrationsRoute,
  ApiTournamentsRoute: ApiTournamentsRoute,
  HealthDatabaseRoute: HealthDatabaseRoute,
  ResultsCodeRoute: ResultsCodeRoute,
  WatchCodeRoute: WatchCodeRoute,
  ApiAdminActionRoute: ApiAdminActionRoute,
  ApiAdminLogoRoute: ApiAdminLogoRoute,
  ApiAssetsIdRoute: ApiAssetsIdRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
